// Code generated by tool/convert
// DO NOT EDIT!
package data

import (
	"sync/atomic"
	"unsafe"
)

type Test struct {
	Addr Addr

	Ib map[int]bool

	Id int64

	Ids []int64

	Ii map[int]int

	Interval int

	Intervals []int

	Is map[int]string

	IsFalse bool

	IsFalses []bool

	Ist map[int]struct{}

	MsgTypeMap map[string][]string

	Names []string

	Rate float64

	Rates []float64

	Si map[string]int

	Ss map[string]string

	Sst map[string]struct{}

	Timeout string
}

var TestPtr unsafe.Pointer = unsafe.Pointer(&Test{})

func CurrentTest() *Test {
	return (*Test)(atomic.LoadPointer(&TestPtr))
}

func UpdateTest(v *Test) {
	atomic.StorePointer(&TestPtr, unsafe.Pointer(v))
}
