// Code generated by tool/convert
// DO NOT EDIT!
package data

import (
	"sync/atomic"
	"unsafe"
)

type Agent struct {
	BasePath string

	ComponentBinPath string

	ComponentLogPath string
}

var AgentPtr unsafe.Pointer = unsafe.Pointer(&Agent{})

func CurrentAgent() *Agent {
	return (*Agent)(atomic.LoadPointer(&AgentPtr))
}

func UpdateAgent(v *Agent) {
	atomic.StorePointer(&AgentPtr, unsafe.Pointer(v))
}
