// Code generated by tool/convert
// DO NOT EDIT!
package data

import (
	"sync/atomic"
	"unsafe"
)

type Test struct {
	HttpTimeout string

	MsgTypeMap map[string][]string

	TcpReadTimeout string

	TcpTimeout string

	TcpWriteTimeout string

	Timeout string
}

var TestPtr unsafe.Pointer = unsafe.Pointer(&Test{})

func CurrentTest() *Test {
	return (*Test)(atomic.LoadPointer(&TestPtr))
}

func UpdateTest(v *Test) {
	atomic.StorePointer(&TestPtr, unsafe.Pointer(v))
}
