package main

var tplStruct = `
// Code generated by tool/convert
// DO NOT EDIT!
package data

import (
	"sync/atomic"
	"unsafe"
	{{range $index, $library := .Libraries}}
	"{{$library}}"
	{{end}}
)

type {{.Name}} struct {
	{{range $index, $element := .Data}}
	{{$element.StructKey}} {{$element.Type}}
	{{end}}
}

var {{.Name}}Ptr unsafe.Pointer = unsafe.Pointer(&{{.Name}}{})

func Current{{.Name}}() *{{.Name}} {
	return (*{{.Name}})(atomic.LoadPointer(&{{.Name}}Ptr))
}

func Update{{.Name}}(v *{{.Name}}) {
	atomic.StorePointer(&{{.Name}}Ptr, unsafe.Pointer(v))
}
`
