package main

var tplMeta = `
// Code generated by tool/convert
// DO NOT EDIT!
package data

type container struct {
	s map[string]interface{}
}

func (c *container) Update(name string, st interface{}) error {
	switch name {
	{{range $index, $element := .}}
	case "{{$element.Name}}":
		tmp := st.(*{{$element.Name}})
		Update{{$element.Name}}(tmp)
	{{end}}
	default:
		panic("unsupported struct " + name)
	}
	return nil
}

func (c *container) GetStructs() map[string]interface{} {
	return c.s
}

var ObjectsContainer = &container{
	s: map[string]interface{}{
		{{range $index, $element := .}}
		"{{$element.Name}}": {{$element.Name}}{},
		{{end}}
	},
}
`
